-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-09-14 21:56:18 SGT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

--student id: 29799260
--student name: Morad Abou Shadi

--capture run of script in file called mm_schema_output.txt
set echo on
SPOOL mm_schema_output.txt

DROP TABLE assessments CASCADE CONSTRAINTS;

DROP TABLE attendance CASCADE CONSTRAINTS;

DROP TABLE class CASCADE CONSTRAINTS;

DROP TABLE class_description CASCADE CONSTRAINTS;

DROP TABLE class_staffing CASCADE CONSTRAINTS;

DROP TABLE enrollment CASCADE CONSTRAINTS;

DROP TABLE facility CASCADE CONSTRAINTS;

DROP TABLE fitness_centre CASCADE CONSTRAINTS;

DROP TABLE member CASCADE CONSTRAINTS;

DROP TABLE role CASCADE CONSTRAINTS;

DROP TABLE staff CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE assessments (
    member_id             NUMBER(4) NOT NULL,
    assessment_date       DATE NOT NULL,
    member_weight         NUMBER(3) NOT NULL,
    member_bloodpressure  VARCHAR2(6) NOT NULL,
    member_bmi            NUMBER(3, 1) NOT NULL,
    memberr_vo2max        VARCHAR2(3) NOT NULL,
    staff_id              NUMBER(5) NOT NULL
);

COMMENT ON COLUMN assessments.member_id IS
    'member ID';

COMMENT ON COLUMN assessments.assessment_date IS
    'date of assessment';

COMMENT ON COLUMN assessments.member_weight IS
    'weight of member';

COMMENT ON COLUMN assessments.member_bloodpressure IS
    'blood prressure reading';

COMMENT ON COLUMN assessments.member_bmi IS
    'BMI';

COMMENT ON COLUMN assessments.memberr_vo2max IS
    'VO2Max reading';

COMMENT ON COLUMN assessments.staff_id IS
    'staff ID';

ALTER TABLE assessments ADD CONSTRAINT assessments_pk PRIMARY KEY ( assessment_date,
                                                                    member_id );

CREATE TABLE attendance (
    attendance_no          NUMBER(4) NOT NULL,
    class_numb             NUMBER(3) NOT NULL,
    centre_id              NUMBER(3) NOT NULL,
    class_start_date_time  DATE NOT NULL,
    member_id              NUMBER(4) NOT NULL,
    sessioin_date          DATE NOT NULL,
    total_attendance       NUMBER(2) NOT NULL
);

COMMENT ON COLUMN attendance.attendance_no IS
    'surrogate key';

COMMENT ON COLUMN attendance.class_numb IS
    'class number';

COMMENT ON COLUMN attendance.centre_id IS
    'Centre ID';

COMMENT ON COLUMN attendance.class_start_date_time IS
    'starrt date and time of class';

COMMENT ON COLUMN attendance.member_id IS
    'member ID';

COMMENT ON COLUMN attendance.sessioin_date IS
    'Date of session';

COMMENT ON COLUMN attendance.total_attendance IS
    'total attendance of this member for this class';

ALTER TABLE attendance ADD CONSTRAINT attendance_pk PRIMARY KEY ( attendance_no );

ALTER TABLE attendance
    ADD CONSTRAINT attendance_nk UNIQUE ( class_numb,
                                          centre_id,
                                          class_start_date_time,
                                          member_id,
                                          sessioin_date );

CREATE TABLE class (
    class_numb                 NUMBER(3) NOT NULL,
    centre_id                  NUMBER(3) NOT NULL,
    class_start_date_time      DATE NOT NULL,
    class_max_participants     NUMBER(3),
    class_sessions             NUMBER(2) NOT NULL,
    class_cost                 NUMBER(5, 2) NOT NULL,
    class_type                 VARCHAR2(8) NOT NULL,
    facility_room_numb         NUMBER(3) NOT NULL,
    class_gender_restrictions  CHAR(1) NOT NULL
);

ALTER TABLE class
    ADD CONSTRAINT chk_gender CHECK ( class_gender_restrictions IN ( '-', 'F', 'M' ) );

COMMENT ON COLUMN class.class_numb IS
    'class number';

COMMENT ON COLUMN class.centre_id IS
    'Centre ID';

COMMENT ON COLUMN class.class_start_date_time IS
    'starrt date and time of class';

COMMENT ON COLUMN class.class_max_participants IS
    'max participants';

COMMENT ON COLUMN class.class_sessions IS
    'total number of sessions';

COMMENT ON COLUMN class.class_cost IS
    'cost of class';

COMMENT ON COLUMN class.class_type IS
    'type of class';

COMMENT ON COLUMN class.facility_room_numb IS
    'room number';

COMMENT ON COLUMN class.class_gender_restrictions IS
    'does the class have any gender restrictions?';

ALTER TABLE class
    ADD CONSTRAINT class_pk PRIMARY KEY ( class_numb,
                                          centre_id,
                                          class_start_date_time );

CREATE TABLE class_description (
    class_type  VARCHAR2(8) NOT NULL,
    class_desc  VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN class_description.class_type IS
    'type of class';

COMMENT ON COLUMN class_description.class_desc IS
    'descriptioon of class';

ALTER TABLE class_description ADD CONSTRAINT class_description_pk PRIMARY KEY ( class_type );

CREATE TABLE class_staffing (
    class_staffing_no      NUMBER(4) NOT NULL,
    staff_id               NUMBER(5) NOT NULL,
    class_numb             NUMBER(3) NOT NULL,
    centre_id              NUMBER(3) NOT NULL,
    class_start_date_time  DATE NOT NULL,
    class_leader           CHAR(1) NOT NULL
);

COMMENT ON COLUMN class_staffing.class_staffing_no IS
    'surrogate key';

COMMENT ON COLUMN class_staffing.staff_id IS
    'staff ID';

COMMENT ON COLUMN class_staffing.class_numb IS
    'class number';

COMMENT ON COLUMN class_staffing.centre_id IS
    'Centre ID';

COMMENT ON COLUMN class_staffing.class_start_date_time IS
    'starrt date and time of class';

COMMENT ON COLUMN class_staffing.class_leader IS
    'is this staff member the class leader';

ALTER TABLE class_staffing ADD CONSTRAINT classs_staffing_pk PRIMARY KEY ( class_staffing_no );

ALTER TABLE class_staffing
    ADD CONSTRAINT class_staffing_nk UNIQUE ( staff_id,
                                              class_numb,
                                              centre_id,
                                              class_start_date_time );

CREATE TABLE enrollment (
    enrollment_no            NUMBER(4) NOT NULL,
    member_id                NUMBER(4) NOT NULL,
    class_numb               NUMBER(3) NOT NULL,
    centre_id                NUMBER(3) NOT NULL,
    class_start_date_time    DATE NOT NULL,
    enrollment_payment_date  DATE NOT NULL
);

COMMENT ON COLUMN enrollment.enrollment_no IS
    'surrogate key';

COMMENT ON COLUMN enrollment.member_id IS
    'member ID';

COMMENT ON COLUMN enrollment.class_numb IS
    'class number';

COMMENT ON COLUMN enrollment.centre_id IS
    'Centre ID';

COMMENT ON COLUMN enrollment.class_start_date_time IS
    'starrt date and time of class';

COMMENT ON COLUMN enrollment.enrollment_payment_date IS
    'date of payment';

ALTER TABLE enrollment ADD CONSTRAINT enrollment_pk PRIMARY KEY ( enrollment_no );

ALTER TABLE enrollment
    ADD CONSTRAINT enrollment_nk UNIQUE ( member_id,
                                          class_numb,
                                          centre_id,
                                          class_start_date_time,
                                          enrollment_payment_date );

CREATE TABLE facility (
    centre_id           NUMBER(3) NOT NULL,
    facility_room_numb  NUMBER(3) NOT NULL,
    facilty_name        VARCHAR2(10) NOT NULL,
    facility_desc       VARCHAR2(20),
    facility_capacity   NUMBER(3) NOT NULL
);

COMMENT ON COLUMN facility.centre_id IS
    'Centre ID';

COMMENT ON COLUMN facility.facility_room_numb IS
    'room number';

COMMENT ON COLUMN facility.facilty_name IS
    'name';

COMMENT ON COLUMN facility.facility_desc IS
    'description';

COMMENT ON COLUMN facility.facility_capacity IS
    'capacity';

ALTER TABLE facility ADD CONSTRAINT facility_pk PRIMARY KEY ( facility_room_numb,
                                                              centre_id );

CREATE TABLE fitness_centre (
    centre_id      NUMBER(3) NOT NULL,
    centre_name    VARCHAR2(10) NOT NULL,
    centre_street  VARCHAR2(8) NOT NULL,
    centre_town    VARCHAR2(8) NOT NULL,
    centre_post    VARCHAR2(8) NOT NULL,
    centre_phone   NUMBER(8),
    staff_id       NUMBER(5) NOT NULL
);

COMMENT ON COLUMN fitness_centre.centre_id IS
    'Centre ID';

COMMENT ON COLUMN fitness_centre.centre_name IS
    'centre name';

COMMENT ON COLUMN fitness_centre.centre_street IS
    'centre street name';

COMMENT ON COLUMN fitness_centre.centre_town IS
    'centre town name';

COMMENT ON COLUMN fitness_centre.centre_post IS
    'centre post office';

COMMENT ON COLUMN fitness_centre.centre_phone IS
    'centre contact number';

COMMENT ON COLUMN fitness_centre.staff_id IS
    'staff ID';

CREATE UNIQUE INDEX fitness_centre__idx ON
    fitness_centre (
        staff_id
    ASC );

ALTER TABLE fitness_centre ADD CONSTRAINT fitness_centre_pk PRIMARY KEY ( centre_id );

CREATE TABLE member (
    member_id         NUMBER(4) NOT NULL,
    member_fname      VARCHAR2(10),
    member_lname      VARCHAR2(10),
    memberr_address   VARCHAR2(50) NOT NULL,
    member_phone      NUMBER(8) NOT NULL,
    member_join_date  DATE NOT NULL,
    centre_id         NUMBER NOT NULL
);

COMMENT ON COLUMN member.member_id IS
    'member ID';

COMMENT ON COLUMN member.member_fname IS
    'first name';

COMMENT ON COLUMN member.member_lname IS
    'last name';

COMMENT ON COLUMN member.memberr_address IS
    'address';

COMMENT ON COLUMN member.member_phone IS
    'phone number';

COMMENT ON COLUMN member.member_join_date IS
    'date the memberr joined';

COMMENT ON COLUMN member.centre_id IS
    'Centre ID';

ALTER TABLE member ADD CONSTRAINT member_pk PRIMARY KEY ( member_id );

CREATE TABLE role (
    role_id    CHAR(1) NOT NULL,
    role_name  VARCHAR2(10) NOT NULL
);

ALTER TABLE role
    ADD CONSTRAINT chk_role CHECK ( role_id IN ( 'A', 'C', 'D', 'M', 'P',
                                                 'S', 'T' ) );

COMMENT ON COLUMN role.role_id IS
    'role ID';

COMMENT ON COLUMN role.role_name IS
    'name of the role';

ALTER TABLE role ADD CONSTRAINT role_pk PRIMARY KEY ( role_id );

CREATE TABLE staff (
    staff_id             NUMBER(5) NOT NULL,
    staff_fname          VARCHAR2(10),
    staff_lname          VARCHAR2(10),
    staff_phone          NUMBER(8) NOT NULL,
    staff_startdate      DATE NOT NULL,
    first_aid_certified  CHAR(1) NOT NULL,
    centre_id            NUMBER NOT NULL,
    role_id              CHAR(1) NOT NULL
);

ALTER TABLE staff
    ADD CONSTRAINT chk_first_aid CHECK ( first_aid_certified IN ( 'N', 'Y' ) );

COMMENT ON COLUMN staff.staff_id IS
    'staff ID';

COMMENT ON COLUMN staff.staff_fname IS
    'first name';

COMMENT ON COLUMN staff.staff_lname IS
    'last name';

COMMENT ON COLUMN staff.staff_phone IS
    'phone number';

COMMENT ON COLUMN staff.staff_startdate IS
    'start date';

COMMENT ON COLUMN staff.first_aid_certified IS
    'is the staff member first aid certified?';

COMMENT ON COLUMN staff.centre_id IS
    'Centre ID';

COMMENT ON COLUMN staff.role_id IS
    'role ID';

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( staff_id );

ALTER TABLE facility
    ADD CONSTRAINT centre_facility FOREIGN KEY ( centre_id )
        REFERENCES fitness_centre ( centre_id )
            ON DELETE CASCADE;

ALTER TABLE member
    ADD CONSTRAINT centre_member FOREIGN KEY ( centre_id )
        REFERENCES fitness_centre ( centre_id );

ALTER TABLE staff
    ADD CONSTRAINT centre_staff FOREIGN KEY ( centre_id )
        REFERENCES fitness_centre ( centre_id );

ALTER TABLE attendance
    ADD CONSTRAINT class_attendance FOREIGN KEY ( class_numb,
                                                  centre_id,
                                                  class_start_date_time )
        REFERENCES class ( class_numb,
                           centre_id,
                           class_start_date_time );

ALTER TABLE class_staffing
    ADD CONSTRAINT class_classstaffing FOREIGN KEY ( class_numb,
                                                     centre_id,
                                                     class_start_date_time )
        REFERENCES class ( class_numb,
                           centre_id,
                           class_start_date_time );

ALTER TABLE enrollment
    ADD CONSTRAINT class_enrollment FOREIGN KEY ( class_numb,
                                                  centre_id,
                                                  class_start_date_time )
        REFERENCES class ( class_numb,
                           centre_id,
                           class_start_date_time )
            ON DELETE CASCADE;

ALTER TABLE class
    ADD CONSTRAINT facility_class FOREIGN KEY ( facility_room_numb,
                                                centre_id )
        REFERENCES facility ( facility_room_numb,
                              centre_id );

ALTER TABLE assessments
    ADD CONSTRAINT member_assessment FOREIGN KEY ( member_id )
        REFERENCES member ( member_id );

ALTER TABLE attendance
    ADD CONSTRAINT member_attendance FOREIGN KEY ( member_id )
        REFERENCES member ( member_id );

ALTER TABLE enrollment
    ADD CONSTRAINT member_enrollment FOREIGN KEY ( member_id )
        REFERENCES member ( member_id )
            ON DELETE CASCADE;

ALTER TABLE staff
    ADD CONSTRAINT role_staff FOREIGN KEY ( role_id )
        REFERENCES role ( role_id );

ALTER TABLE assessments
    ADD CONSTRAINT staff_assessment FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE fitness_centre
    ADD CONSTRAINT staff_centre FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE class_staffing
    ADD CONSTRAINT staff_classstaffing FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE class
    ADD CONSTRAINT type_class FOREIGN KEY ( class_type )
        REFERENCES class_description ( class_type );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             1
-- ALTER TABLE                             32
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off